=== jaimejl21/Gesti-n_Datos/Practica2_G5/XML_XSD_G5/club.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="clubes">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="club" maxOccurs="unbounded">
            <xs:complexType>
            <xs:sequence>
                <xs:element name="trofeos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="trofeo"  maxOccurs="unbounded">
                                <xs:complexType>
                                
                                   
                                    <xs:attribute name="edicion" use="required" type="xs:string"/>  
                                    <xs:attribute name="nombreTrofeo" use="required" type="xs:string"/>  
                                   
            
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>

                </xs:element>
              

            </xs:sequence>  
            <xs:attribute name="nombreC" use="required" type="xs:ID"/>  
            </xs:complexType>

        </xs:element>


    </xs:sequence>    
    </xs:complexType>
    <xs:key name="trofeos">
        <xs:selector xpath="club/trofeos/trofeo"/>
        <xs:field xpath="@edicion"/>
        <xs:field xpath="@nombreTrofeo"/>
    
      </xs:key>
</xs:element>



</xs:schema>

=== jaimejl21/Gesti-n_Datos/Practica2_G5/XML_XSD_G5/club.xml
<?xml version="1.0" encoding="UTF-8" ?>

<clubes xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="club.xsd">
    <club nombreC='Dropkick'>
		<trofeos>
			<trofeo edicion='2017' nombreTrofeo='Campeonato canadiense'/>
		</trofeos>
	</club>
 
	<club nombreC='DrugstoreCowboy'>
		<trofeos>
			<trofeo edicion='2019' nombreTrofeo='Copa de los presdidentes'/>
			<trofeo edicion='2016' nombreTrofeo='Indian Super League'/>
		</trofeos>
	</club>
 
	<club nombreC='DuckDuck'>
		<trofeos>
			<trofeo edicion='2019' nombreTrofeo='USL Champions'/>
		</trofeos>
	</club>
 
	<club nombreC='EarlofArms'>
		<trofeos>
			<trofeo edicion='2018' nombreTrofeo='Indian Super League'/>
		</trofeos>
	</club>
 
	<club nombreC='EasySweep'>
		<trofeos>
			<trofeo edicion='2018' nombreTrofeo='Superliga'/>
			<trofeo edicion='2016' nombreTrofeo='UEFA Champions League'/>
		</trofeos>
	</club>
 
	<club nombreC='EerieMizzen'>
		<trofeos>
			<trofeo edicion='2017' nombreTrofeo='GNF'/>
			<trofeo edicion='2016' nombreTrofeo='Super Copa'/>
			<trofeo edicion='2018' nombreTrofeo='Liga K'/>
		</trofeos>
	</club>
 
	<club nombreC='ElactixNova'>
		<trofeos>
			<trofeo edicion='2018' nombreTrofeo='KNVB Beker'/>
		</trofeos>
	</club>
 
	<club nombreC='ElderPogue'>
		<trofeos>
			<trofeo edicion='2021' nombreTrofeo='Superliga'/>
		</trofeos>
	</club>
 
	<club nombreC='ElectricPlayer'>
		<trofeos>
			<trofeo edicion='2021' nombreTrofeo='Indian Super League'/>
			<trofeo edicion='2021' nombreTrofeo='CSL'/>
			<trofeo edicion='2018' nombreTrofeo='Campeonato canadiense'/>
		</trofeos>
	</club>
 
	<club nombreC='ElectricSaturn'>
		<trofeos>
			<trofeo edicion='2020' nombreTrofeo='UEFA Champions League'/>
		</trofeos>
	</club>
 
	<club nombreC='EmberRope'>
		<trofeos>
			<trofeo edicion='2017' nombreTrofeo='Copa Mx'/>
			<trofeo edicion='2018' nombreTrofeo='Ekstraklasa'/>
			<trofeo edicion='2021' nombreTrofeo='Copa Chile'/>
		</trofeos>
	</club>
 
	<club nombreC='Esquire'>
		<trofeos>
			<trofeo edicion='2016' nombreTrofeo='Copa de Malasia'/>
		</trofeos>
	</club>
 
	<club nombreC='ExoticAlpha'>
		<trofeos>
			<trofeo edicion='2020' nombreTrofeo='Copa Emperador'/>
			<trofeo edicion='2018' nombreTrofeo='GNF'/>
		</trofeos>
	</club>
 
	<club nombreC='EyeShooter'>
		<trofeos>
			<trofeo edicion='2017' nombreTrofeo='HKFA'/>
		</trofeos>
	</club>
 
	<club nombreC='Fabulous'>
		<trofeos>
			<trofeo edicion='2018' nombreTrofeo='Bundesliga'/>
			<trofeo edicion='2019' nombreTrofeo='LaLiga'/>
		</trofeos>
	</club>
 
	<club nombreC='FastDraw'>
		<trofeos>
			<trofeo edicion='2018' nombreTrofeo='PSL'/>
			<trofeo edicion='2018' nombreTrofeo='Coppa Italia'/>
		</trofeos>
	</club>
 
	<club nombreC='FastLane'>
		<trofeos>
			<trofeo edicion='2020' nombreTrofeo='Primeira Liga'/>
			<trofeo edicion='2017' nombreTrofeo='CSL'/>
		</trofeos>
	</club>
 
	<club nombreC='FatherAbbot'>
		<trofeos>
			<trofeo edicion='2017' nombreTrofeo='Coupe de France'/>
			<trofeo edicion='2017' nombreTrofeo='USL Champions'/>
			<trofeo edicion='2020' nombreTrofeo='Eurocopa'/>
		</trofeos>
	</club>
 
	<club nombreC='FenderBoyXXX'>
		<trofeos>
			<trofeo edicion='2020' nombreTrofeo='Copa Chile'/>
		</trofeos>
	</club>
 
	<club nombreC='FennelDove'>
		<trofeos>
			<trofeo edicion='2020' nombreTrofeo='USL Champions'/>
		</trofeos>
	</club>
 
	<club nombreC='FeralMayhem'>
		<trofeos>
			<trofeo edicion='2016' nombreTrofeo='Copa Argentina'/>
			<trofeo edicion='2019' nombreTrofeo='Copa Mx'/>
		</trofeos>
	</club>
 
	<club nombreC='FiendOblivion'>
		<trofeos>
			<trofeo edicion='2017' nombreTrofeo='Liga J1'/>
			<trofeo edicion='2021' nombreTrofeo='Liga Mx'/>
		</trofeos>
	</club>
 
	<club nombreC='FifthHarmony'>
		<trofeos>
			<trofeo edicion='2021' nombreTrofeo='Coupe de la Ligue'/>
		</trofeos>
	</club>
 
	<club nombreC='FireFeline'>
		<trofeos>
			<trofeo edicion='2021' nombreTrofeo='Vietnam League'/>
		</trofeos>
	</club>
 
	<club nombreC='FireFish'>
		<trofeos>
			<trofeo edicion='2021' nombreTrofeo='Serie A'/>
		</trofeos>
	</club>
 
	<club nombreC='FireByMisFire'>
		<trofeos>
			<trofeo edicion='2020' nombreTrofeo='Supercopa Mx'/>
		</trofeos>
	</club>
 
	<club nombreC='FistWizard'>
		<trofeos>
			<trofeo edicion='2017' nombreTrofeo='Copa de Malasia'/>
			<trofeo edicion='2021' nombreTrofeo='UEFA Champions League'/>
		</trofeos>
	</club>
 
	<club nombreC='Flakes'>
		<trofeos>
			<trofeo edicion='2019' nombreTrofeo='MLS'/>
		</trofeos>
	</club>
 
	<club nombreC='FlameOUT'>
		<trofeos>
			<trofeo edicion='2020' nombreTrofeo='Coupe Federation'/>
			<trofeo edicion='2020' nombreTrofeo='Copa de Malasia'/>
		</trofeos>
	</club>
 
	<club nombreC='Flint'>
		<trofeos>
			<trofeo edicion='2019' nombreTrofeo='NASL'/>
		</trofeos>
	</club>
 
	<club nombreC='FlyGuardX'>
		<trofeos>
			<trofeo edicion='2016' nombreTrofeo='Coupe de France'/>
			<trofeo edicion='2018' nombreTrofeo='Copa del Rey'/>
		</trofeos>
	</club>
 
	<club nombreC='FlyingDoodle'>
		<trofeos>
			<trofeo edicion='2016' nombreTrofeo='Ligi kuu Bara'/>
			<trofeo edicion='2020' nombreTrofeo='Liga de estrellas'/>
		</trofeos>
	</club>
 
	<club nombreC='FrankenGrin'>
		<trofeos>
			<trofeo edicion='2020' nombreTrofeo='Coupe de la Ligue'/>
			<trofeo edicion='2021' nombreTrofeo='Magyar Kupa'/>
		</trofeos>
	</club>
 
	<club nombreC='Freak'>
		<trofeos>
			<trofeo edicion='2018' nombreTrofeo='MLS'/>
		</trofeos>
	</club>
 
	<club nombreC='FrozenExplosion'>
		<trofeos>
			<trofeo edicion='2021' nombreTrofeo='Ligi kuu Bara'/>
		</trofeos>
	</club>
 
	<club nombreC='Gadget'>
		<trofeos>
			<trofeo edicion='2018' nombreTrofeo='Serie A'/>
		</trofeos>
	</club>
 
	<club nombreC='GasMan'>
		<trofeos>
			<trofeo edicion='2016' nombreTrofeo='Eredivisie'/>
			<trofeo edicion='2020' nombreTrofeo='Liga S'/>
			<trofeo edicion='2016' nombreTrofeo='Liga de estrellas'/>
		</trofeos>
	</club>
 
	<club nombreC='GeneralBroomdog'>
		<trofeos>
			<trofeo edicion='2019' nombreTrofeo='Coupe Federation'/>
		</trofeos>
	</club>
 
	<club nombreC='GeneralFinish'>
		<trofeos>
			<trofeo edicion='2021' nombreTrofeo='Copa Emperador'/>
			<trofeo edicion='2020' nombreTrofeo='LaLiga'/>
		</trofeos>
	</club>
 
	<club nombreC='Ghostrider'>
		<trofeos>
			<trofeo edicion='2020' nombreTrofeo='Copa Colombia'/>
			<trofeo edicion='2019' nombreTrofeo='UEFA Europa League'/>
		</trofeos>
	</club>
 
	<club nombreC='Globalmeltdown'>
		<trofeos>
			<trofeo edicion='2018' nombreTrofeo='Liga Mx'/>
			<trofeo edicion='2020' nombreTrofeo='Serie A'/>
		</trofeos>
	</club>
 
	<club nombreC='Glyph'>
		<trofeos>
			<trofeo edicion='2018' nombreTrofeo='Copa de Singapur'/>
			<trofeo edicion='2019' nombreTrofeo='CSL'/>
		</trofeos>
	</club>
 
	<club nombreC='GoateeShield'>
		<trofeos>
			<trofeo edicion='2020' nombreTrofeo='Liga K'/>
		</trofeos>
	</club>
 
	<club nombreC='GovSkull'>
		<trofeos>
			<trofeo edicion='2019' nombreTrofeo='Liga J1'/>
			<trofeo edicion='2018' nombreTrofeo='Thai League'/>
		</trofeos>
	</club>
 
	<club nombreC='GraveDigger'>
		<trofeos>
			<trofeo edicion='2020' nombreTrofeo='Copa Mx'/>
		</trofeos>
	</club>
 
	<club nombreC='GreekRifle'>
		<trofeos>
			<trofeo edicion='2020' nombreTrofeo='Eredivisie'/>
		</trofeos>
	</club>
 
	<club nombreC='GreenGhost'>
		<trofeos>
			<trofeo edicion='2021' nombreTrofeo='Copa del Rey'/>
			<trofeo edicion='2017' nombreTrofeo='Copa Emperador'/>
		</trofeos>
	</club>
 
	<club nombreC='GreenScavenger'>
		<trofeos>
			<trofeo edicion='2021' nombreTrofeo='Supercopa Mx'/>
		</trofeos>
	</club>
 
	<club nombreC='Guillotine'>
		<trofeos>
			<trofeo edicion='2016' nombreTrofeo='Copa Chile'/>
			<trofeo edicion='2017' nombreTrofeo='NASL'/>
		</trofeos>
	</club>
 
	<club nombreC='Gullyway'>
		<trofeos>
			<trofeo edicion='2017' nombreTrofeo='Divisi Utama'/>
			<trofeo edicion='2019' nombreTrofeo='Copa del Rey'/>
			<trofeo edicion='2019' nombreTrofeo='Supercopa Mx'/>
		</trofeos>
	</club>
 
	<club nombreC='GuncapSlingbad'>
		<trofeos>
			<trofeo edicion='2017' nombreTrofeo='Copa del Rey'/>
			<trofeo edicion='2017' nombreTrofeo='UEFA Champions League'/>
		</trofeos>
	</club>
 
	<club nombreC='Gunhawk'>
		<trofeos>
			<trofeo edicion='2020' nombreTrofeo='Ekstraklasa'/>
			<trofeo edicion='2016' nombreTrofeo='MLS'/>
		</trofeos>
	</club>
 
	<club nombreC='HeroOfBlackday'>
		<trofeos>
			<trofeo edicion='2019' nombreTrofeo='Coppa Italia'/>
		</trofeos>
	</club>
 
	<club nombreC='HighKingdomWarrior'>
		<trofeos>
			<trofeo edicion='2019' nombreTrofeo='Campeonato canadiense'/>
			<trofeo edicion='2021' nombreTrofeo='Liga S'/>
			<trofeo edicion='2018' nombreTrofeo='Premier League'/>
		</trofeos>
	</club>
 
	<club nombreC='HighlanderMonk'>
		<trofeos>
			<trofeo edicion='2018' nombreTrofeo='USL Champions'/>
			<trofeo edicion='2021' nombreTrofeo='Bundesliga'/>
		</trofeos>
	</club>
 
	<club nombreC='Hightower'>
		<trofeos>
			<trofeo edicion='2021' nombreTrofeo='Primeira Liga'/>
			<trofeo edicion='2016' nombreTrofeo='Liga S'/>
		</trofeos>
	</club>
 
	<club nombreC='HogButcher'>
		<trofeos>
			<trofeo edicion='2019' nombreTrofeo='UEFA Champions League'/>
			<trofeo edicion='2020' nombreTrofeo='Ligi kuu Bara'/>
		</trofeos>
	</club>
 
	<club nombreC='HollySparta'>
		<trofeos>
			<trofeo edicion='2017' nombreTrofeo='Liga de estrellas'/>
			<trofeo edicion='2018' nombreTrofeo='Coupe de la Ligue'/>
		</trofeos>
	</club>
 
	<club nombreC='Houston'>
		<trofeos>
			<trofeo edicion='2018' nombreTrofeo='Copa Argentina'/>
			<trofeo edicion='2021' nombreTrofeo='Copa de los presdidentes'/>
