=== jaimejl21/Gesti-n_Datos/Practica2_G5/XML_XSD_G5/compras.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="compras">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="compra" maxOccurs="unbounded">
                <xs:complexType>
                <xs:sequence>
                    <xs:element name="usuario" minOccurs="1" maxOccurs="1" type="xs:string"/>
                    <xs:element name="articulo" minOccurs="1" maxOccurs="unbounded">
                       <xs:complexType>
                       <xs:sequence>
                        <xs:element name="nombreArticulo" minOccurs="1" maxOccurs="1" type="xs:string"/>
                        <xs:element name="tipoArticulo" minOccurs="1" maxOccurs="1" type="xs:string"/>
                        <xs:element name="cantidad" minOccurs="1" maxOccurs="1" type="xs:int"/>
                        <xs:element name="precio" minOccurs="1" maxOccurs="1" type="xs:int"/>
                       </xs:sequence>    
                       </xs:complexType> 
                    </xs:element>


                </xs:sequence> 
                   
                <xs:attribute name="idCompra" use="required" >
                    <xs:simpleType>
                     <xs:restriction base="xs:ID">
                        <xs:pattern value="[c][o][m][p][r][a][-][0-9][0-9][0-9]"></xs:pattern>
                     </xs:restriction>
                    </xs:simpleType>   
                </xs:attribute>

                </xs:complexType>
            </xs:element>


        </xs:sequence>  
        </xs:complexType>

    </xs:element>





</xs:schema>

=== jaimejl21/Gesti-n_Datos/Practica2_G5/XML_XSD_G5/compras.xml
<?xml version="1.0" encoding="UTF-8" ?>

<compras xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="compras.xsd">
  <compra idCompra='compra-001'>
    <usuario>BeardedAngler</usuario>
    <articulo>
      <nombreArticulo>Guante</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>3</cantidad>
      <precio>30</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Centinela</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>3</cantidad>
      <precio>30</precio>
    </articulo>
    <articulo>
      <nombreArticulo>The Bear (Ronaldo)</nombreArticulo>
      <tipoArticulo>Baile</tipoArticulo>
      <cantidad>1</cantidad>
      <precio>5</precio>
    </articulo>
  </compra>
  
  <compra idCompra='compra-002'>
    <usuario>CelticCharger</usuario>
    <articulo>
      <nombreArticulo>Allianz Arena</nombreArticulo>
      <tipoArticulo>Estadio</tipoArticulo>
      <cantidad>8</cantidad>
      <precio>56</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Gladiador</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>7</cantidad>
      <precio>70</precio>
    </articulo>
  </compra>
  <compra idCompra='compra-003'>
    <usuario>DayHawk</usuario>
    <articulo>
      <nombreArticulo>Ancla</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>5</cantidad>
      <precio>50</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Francotirador</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>6</cantidad>
      <precio>60</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Motorbike</nombreArticulo>
      <tipoArticulo>Baile</tipoArticulo>
      <cantidad>9</cantidad>
      <precio>45</precio>
    </articulo>
  </compra>
  <compra idCompra='compra-004'>
    <usuario>AtomicBlastoid</usuario>
    <articulo>
      <nombreArticulo>The Worm</nombreArticulo>
      <tipoArticulo>Baile</tipoArticulo>
      <cantidad>4</cantidad>
      <precio>20</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Tirador</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>4</cantidad>
      <precio>40</precio>
    </articulo>
  </compra>
  <compra idCompra='compra-005'>
    <usuario>CelticCharger</usuario>
    <articulo>
      <nombreArticulo>Maestro</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>2</cantidad>
      <precio>20</precio>
    </articulo>
    <articulo>
      <nombreArticulo>The Worm</nombreArticulo>
      <tipoArticulo>Baile</tipoArticulo>
      <cantidad>4</cantidad>
      <precio>20</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Amex Stadium</nombreArticulo>
      <tipoArticulo>Estadio</tipoArticulo>
      <cantidad>7</cantidad>
      <precio>49</precio>
    </articulo>
  </compra>
  <compra idCompra='compra-006'>
    <usuario>DesertHaze</usuario>
    <articulo>
      <nombreArticulo>Aguila</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>2</cantidad>
      <precio>20</precio>
    </articulo>
    <articulo>
      <nombreArticulo>KO(Rooney)</nombreArticulo>
      <tipoArticulo>Baile</tipoArticulo>
      <cantidad>1</cantidad>
      <precio>5</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Muscle Flex (Mario Balotelli)</nombreArticulo>
      <tipoArticulo>Baile</tipoArticulo>
      <cantidad>2</cantidad>
      <precio>10</precio>
    </articulo>
  </compra>
  <compra idCompra='compra-007'>
    <usuario>CoolWhip</usuario>
    <articulo>
      <nombreArticulo>Wembley</nombreArticulo>
      <tipoArticulo>Estadio</tipoArticulo>
      <cantidad>8</cantidad>
      <precio>56</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Right Here Right Now (Ronaldo)</nombreArticulo>
      <tipoArticulo>Baile</tipoArticulo>
      <cantidad>10</cantidad>
      <precio>50</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Protector</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>7</cantidad>
      <precio>70</precio>
    </articulo>
  </compra>
  <compra idCompra='compra-008'>
    <usuario>Cabbie</usuario>
    <articulo>
      <nombreArticulo>Sombra</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>3</cantidad>
      <precio>30</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Maestro</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>7</cantidad>
      <precio>70</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Prancing Bird</nombreArticulo>
      <tipoArticulo>Baile</tipoArticulo>
      <cantidad>7</cantidad>
      <precio>35</precio>
    </articulo>
  </compra>
  <compra idCompra='compra-009'>
    <usuario>AdmiralTot</usuario>
    <articulo>
      <nombreArticulo>Right Here Right Now (Ronaldo)</nombreArticulo>
      <tipoArticulo>Baile</tipoArticulo>
      <cantidad>3</cantidad>
      <precio>15</precio>
    </articulo>
    <articulo>
      <nombreArticulo>The Worm</nombreArticulo>
      <tipoArticulo>Baile</tipoArticulo>
      <cantidad>7</cantidad>
      <precio>35</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Muro</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>9</cantidad>
      <precio>90</precio>
    </articulo>
  </compra>
  <compra idCompra='compra-010'>
    <usuario>CrazyEights</usuario>
    <articulo>
      <nombreArticulo>Protector</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>7</cantidad>
      <precio>70</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Maestro</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>6</cantidad>
      <precio>60</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Arquitecto</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>2</cantidad>
      <precio>20</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Kiss the Wrist</nombreArticulo>
      <tipoArticulo>Baile</tipoArticulo>
      <cantidad>9</cantidad>
      <precio>45</precio>
    </articulo>
  </compra>
  <compra idCompra='compra-011'>
    <usuario>Chuckles</usuario>
    <articulo>
      <nombreArticulo>Rematador</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>1</cantidad>
      <precio>10</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Patty Cake</nombreArticulo>
      <tipoArticulo>Baile</tipoArticulo>
      <cantidad>9</cantidad>
      <precio>45</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Maestro</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>5</cantidad>
      <precio>50</precio>
    </articulo>
  </compra>
  <compra idCompra='compra-012'>
    <usuario>DriftManiac</usuario>
    <articulo>
      <nombreArticulo>Bailando Robot</nombreArticulo>
      <tipoArticulo>Baile</tipoArticulo>
      <cantidad>10</cantidad>
      <precio>50</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Arquitecto</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>8</cantidad>
      <precio>80</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Dance</nombreArticulo>
      <tipoArticulo>Baile</tipoArticulo>
      <cantidad>4</cantidad>
      <precio>20</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Artista</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>1</cantidad>
      <precio>10</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Motorbike</nombreArticulo>
      <tipoArticulo>Baile</tipoArticulo>
      <cantidad>4</cantidad>
      <precio>20</precio>
    </articulo>
  </compra>
  <compra idCompra='compra-013'>
    <usuario>Bowler</usuario>
    <articulo>
      <nombreArticulo>Stamford Bridge</nombreArticulo>
      <tipoArticulo>Estadio</tipoArticulo>
      <cantidad>3</cantidad>
      <precio>21</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Old Man</nombreArticulo>
      <tipoArticulo>Baile</tipoArticulo>
      <cantidad>1</cantidad>
      <precio>5</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Guante</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>10</cantidad>
      <precio>100</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Arquitecto</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>10</cantidad>
      <precio>100</precio>
    </articulo>
  </compra>
  <compra idCompra='compra-014'>
    <usuario>DiamondGamer</usuario>
    <articulo>
      <nombreArticulo>Cazador</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>10</cantidad>
      <precio>100</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Tirador</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>9</cantidad>
      <precio>90</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Potente</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>6</cantidad>
      <precio>60</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Selhurst Park</nombreArticulo>
      <tipoArticulo>Estadio</tipoArticulo>
      <cantidad>7</cantidad>
      <precio>49</precio>
    </articulo>
    <articulo>
      <nombreArticulo>Escudo</nombreArticulo>
      <tipoArticulo>Mejora</tipoArticulo>
      <cantidad>6</cantidad>
      <precio>60</precio>
    </articulo>
  </compra>
  <compra idCompra='compra-015'>
    <usuario>Breadmaker</usuario>
    <articulo>
      <nombreArticulo>Emirates Stadium</nombreArticulo>
      <tipoArticulo>Estadio</tipoArticulo>
      <cantidad>3</cantidad>
