=== jaimejl21/Gesti-n_Datos/Practica2_G5/XML_XSD_G5/futbolistas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="futbolistas">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="futbolista" maxOccurs="unbounded">
                <xs:complexType>
                <xs:sequence>
                    
                    <xs:element name="nombre" minOccurs="1" maxOccurs="1" type="xs:string"/>
                    <xs:element name="equipo" minOccurs="1" maxOccurs="2">
                        <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombreEquipo" minOccurs="1" maxOccurs="1" type="xs:string"/>
                            <xs:element name="pais" minOccurs="1" maxOccurs="1" type="xs:string"/>
                            <xs:element name="liga" minOccurs="1" maxOccurs="1" type="xs:string"/>
                        </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                <!--    <xs:element name="edad" minOccurs="1" maxOccurs="1"  type="xs:int"/>--> 
                    <xs:element name="cartas" minOccurs="1" maxOccurs="1">
                        <xs:complexType>
                        <xs:sequence>
                            <xs:element name="carta" minOccurs="1" maxOccurs="unbounded"  >
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="mediaCarta" minOccurs="1 " maxOccurs="1" type="media"/>
                                    </xs:sequence>
                            <xs:attribute name="tipoCarta" use="required" type="xs:string"/>      
                                      
                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                                           
                        </xs:complexType>
                        </xs:element>
                </xs:sequence>    
                
                <xs:attribute name="idF" use="required" >
                    <xs:simpleType>
                     <xs:restriction base="xs:ID">
                        <xs:pattern value="[f][-][0-9][0-9][0-9]"></xs:pattern>
                     </xs:restriction>
                    </xs:simpleType>   
                </xs:attribute>

                </xs:complexType>
            </xs:element>

        </xs:sequence>

        </xs:complexType>

       <!--  <xs:unique name="cartas">
            <xs:selector xpath="futbolista"/>
            <xs:field   xpath="@idF"/>
            <xs:field xpath="cartas/carta/@tipoCarta"/>
        </xs:unique> 
    -->
       <!--   <xs:keyref name="cartasRef" refer="cartas">
            <xs:selector xpath="futbolista/cartas/carta" />
            <xs:field xpath="@tipoCarta" />
          </xs:keyref>
--> 
    </xs:element>

<xs:simpleType name="media">
    <xs:restriction base="xs:positiveInteger">
        <xs:minInclusive value="1"/>
        <xs:maxInclusive value="99"/>
    </xs:restriction>
</xs:simpleType>



</xs:schema>

=== jaimejl21/Gesti-n_Datos/Practica2_G5/XML_XSD_G5/futbolistas.xml
<?xml version="1.0" encoding="UTF-8" ?>

<futbolistas xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="futbolistas.xsd">

    <futbolista idF='f-001'>
		<nombre>K.Navas</nombre>
		<equipo>
			<nombreEquipo>PSG</nombreEquipo>
			<pais>Francia</pais>
			<liga>PSG</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>90</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-002'>
		<nombre>P.Kimpembe</nombre>
		<equipo>
			<nombreEquipo>PSG</nombreEquipo>
			<pais>Francia</pais>
			<liga>PSG</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>83</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-003'>
		<nombre>A.Diallo</nombre>
		<equipo>
			<nombreEquipo>PSG</nombreEquipo>
			<pais>Francia</pais>
			<liga>PSG</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>88</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-004'>
		<nombre>Marquinhos</nombre>
		<equipo>
			<nombreEquipo>PSG</nombreEquipo>
			<pais>Francia</pais>
			<liga>PSG</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>88</mediaCarta>
			</carta>
			<carta tipoCarta='TOTY'>
				<mediaCarta>96</mediaCarta>
			</carta>
			<carta tipoCarta='Destacados'>
				<mediaCarta>92</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-005'>
		<nombre>A.Florenzi</nombre>
		<equipo>
			<nombreEquipo>PSG</nombreEquipo>
			<pais>Francia</pais>
			<liga>PSG</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>89</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-006'>
		<nombre>L.Paredes</nombre>
		<equipo>
			<nombreEquipo>PSG</nombreEquipo>
			<pais>Francia</pais>
			<liga>PSG</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>85</mediaCarta>
			</carta>
			<carta tipoCarta='TOTY'>
				<mediaCarta>93</mediaCarta>
			</carta>
			<carta tipoCarta='Destacados'>
				<mediaCarta>89</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-007'>
		<nombre>Danilo Pereira</nombre>
		<equipo>
			<nombreEquipo>PSG</nombreEquipo>
			<pais>Francia</pais>
			<liga>PSG</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>90</mediaCarta>
			</carta>
			<carta tipoCarta='TOTY'>
				<mediaCarta>98</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-008'>
		<nombre>M.Verratti</nombre>
		<equipo>
			<nombreEquipo>PSG</nombreEquipo>
			<pais>Francia</pais>
			<liga>PSG</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>90</mediaCarta>
			</carta>
			<carta tipoCarta='TOTY'>
				<mediaCarta>98</mediaCarta>
			</carta>
			<carta tipoCarta='Destacados'>
				<mediaCarta>94</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-009'>
		<nombre>K.Mbappe</nombre>
		<equipo>
			<nombreEquipo>PSG</nombreEquipo>
			<pais>Francia</pais>
			<liga>PSG</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>90</mediaCarta>
			</carta>
			<carta tipoCarta='Destacados'>
				<mediaCarta>94</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-010'>
		<nombre>M.Kean</nombre>
		<equipo>
			<nombreEquipo>PSG</nombreEquipo>
			<pais>Francia</pais>
			<liga>PSG</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>85</mediaCarta>
			</carta>
			<carta tipoCarta='TOTY'>
				<mediaCarta>93</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-011'>
		<nombre>Neymar</nombre>
		<equipo>
			<nombreEquipo>PSG</nombreEquipo>
			<pais>Francia</pais>
			<liga>PSG</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>83</mediaCarta>
			</carta>
			<carta tipoCarta='TOTY'>
				<mediaCarta>91</mediaCarta>
			</carta>
			<carta tipoCarta='Destacados'>
				<mediaCarta>87</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-012'>
		<nombre>M.Ter Stegen</nombre>
		<equipo>
			<nombreEquipo>Barcelona</nombreEquipo>
			<pais>Espana</pais>
			<liga>Barcelona</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>86</mediaCarta>
			</carta>
			<carta tipoCarta='TOTY'>
				<mediaCarta>94</mediaCarta>
			</carta>
			<carta tipoCarta='Destacados'>
				<mediaCarta>90</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-013'>
		<nombre>Jordi Alba</nombre>
		<equipo>
			<nombreEquipo>Barcelona</nombreEquipo>
			<pais>Espana</pais>
			<liga>Barcelona</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>89</mediaCarta>
			</carta>
			<carta tipoCarta='Destacados'>
				<mediaCarta>93</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-014'>
		<nombre>C.Lenglet</nombre>
		<equipo>
			<nombreEquipo>Barcelona</nombreEquipo>
			<pais>Espana</pais>
			<liga>Barcelona</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>84</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-015'>
		<nombre>Pique</nombre>
		<equipo>
			<nombreEquipo>Barcelona</nombreEquipo>
			<pais>Espana</pais>
			<liga>Barcelona</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>86</mediaCarta>
			</carta>
			<carta tipoCarta='Destacados'>
				<mediaCarta>90</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-016'>
		<nombre>Sergi Roberto</nombre>
		<equipo>
			<nombreEquipo>Barcelona</nombreEquipo>
			<pais>Espana</pais>
			<liga>Barcelona</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>90</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-017'>
		<nombre>F.De Jong</nombre>
		<equipo>
			<nombreEquipo>Barcelona</nombreEquipo>
			<pais>Espana</pais>
			<liga>Barcelona</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>86</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-018'>
		<nombre>Busquets</nombre>
		<equipo>
			<nombreEquipo>Barcelona</nombreEquipo>
			<pais>Espana</pais>
			<liga>Barcelona</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>90</mediaCarta>
			</carta>
			<carta tipoCarta='TOTY'>
				<mediaCarta>98</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-019'>
		<nombre>Ansu Fati</nombre>
		<equipo>
			<nombreEquipo>Barcelona</nombreEquipo>
			<pais>Espana</pais>
			<liga>Barcelona</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>84</mediaCarta>
			</carta>
			<carta tipoCarta='TOTY'>
				<mediaCarta>92</mediaCarta>
			</carta>
			<carta tipoCarta='Destacados'>
				<mediaCarta>88</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-020'>
		<nombre>A.Griezmann</nombre>
		<equipo>
			<nombreEquipo>Barcelona</nombreEquipo>
			<pais>Espana</pais>
			<liga>Barcelona</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>89</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-021'>
		<nombre>O.Dembele</nombre>
		<equipo>
			<nombreEquipo>Barcelona</nombreEquipo>
			<pais>Espana</pais>
			<liga>Barcelona</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>88</mediaCarta>
			</carta>
			<carta tipoCarta='Destacados'>
				<mediaCarta>92</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-022'>
		<nombre>L.Messi</nombre>
		<equipo>
			<nombreEquipo>Barcelona</nombreEquipo>
			<pais>Espana</pais>
			<liga>Barcelona</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>91</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-023'>
		<nombre>T.Courtois</nombre>
		<equipo>
			<nombreEquipo>Real Madrid</nombreEquipo>
			<pais>Espana</pais>
			<liga>Real Madrid</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>91</mediaCarta>
			</carta>
			<carta tipoCarta='TOTY'>
				<mediaCarta>99</mediaCarta>
			</carta>
			<carta tipoCarta='Destacados'>
				<mediaCarta>95</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-024'>
		<nombre>Nacho</nombre>
		<equipo>
			<nombreEquipo>Real Madrid</nombreEquipo>
			<pais>Espana</pais>
			<liga>Real Madrid</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>83</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-025'>
		<nombre>R.Varane</nombre>
		<equipo>
			<nombreEquipo>Real Madrid</nombreEquipo>
			<pais>Espana</pais>
			<liga>Real Madrid</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>84</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-026'>
		<nombre>Lucas Vazquez</nombre>
		<equipo>
			<nombreEquipo>Real Madrid</nombreEquipo>
			<pais>Espana</pais>
			<liga>Real Madrid</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>88</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-027'>
		<nombre>Casemiro</nombre>
		<equipo>
			<nombreEquipo>Real Madrid</nombreEquipo>
			<pais>Espana</pais>
			<liga>Real Madrid</liga>
		</equipo>
		<cartas>
			<carta tipoCarta='normal'>
				<mediaCarta>84</mediaCarta>
			</carta>
			<carta tipoCarta='Destacados'>
				<mediaCarta>88</mediaCarta>
			</carta>
		</cartas>
	</futbolista>
 
	<futbolista idF='f-028'>
		<nombre>T.Kross</nombre>
		<equipo>
			<nombreEquipo>Real Madrid</nombreEquipo>
			<pais>Espana</pais>
			<liga>Real Madrid</liga>
		</equipo>
		<cartas>
