=== jaimejl21/Gesti-n_Datos/Practica2_G5/XML_XSD_G5/jugadas.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="partidos">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="partido" maxOccurs="unbounded">
                <xs:complexType>
                 <xs:sequence> 
            <xs:element name="jugadores">
                <xs:complexType>
                <xs:sequence>
                    <xs:element name="jugador" minOccurs="2" maxOccurs="2"></xs:element>
                </xs:sequence>    
                </xs:complexType>
            </xs:element>

            <xs:element name="equipos">
                <xs:complexType>
                <xs:sequence>
                    <xs:element name="equipo" minOccurs="2" maxOccurs="2"></xs:element>
                </xs:sequence>    
                </xs:complexType>
            </xs:element>
            
            <xs:element name="jugadas">
                <xs:complexType>
                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="gol" maxOccurs="unbounded">
                        <xs:complexType>
                        <xs:sequence>
                            <xs:element name="minuto" minOccurs="1" maxOccurs="1" type="xs:string"/>
                                
                            
                            <xs:element name="equipo" minOccurs="1" maxOccurs="1"></xs:element>
                            <xs:element name="futbolista" minOccurs="1" maxOccurs="1"></xs:element>
                            <xs:element name="tipo" minOccurs="0" maxOccurs="1">
                                <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Penalti"/>
                                    <xs:enumeration value="En propia"/>
                                </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>    
                        </xs:complexType>
                    </xs:element>

                    <xs:element name="tarjeta">
                        <xs:complexType>
                        <xs:sequence>
                            <xs:element name="minuto" minOccurs="1" maxOccurs="1" type="xs:string"/>
                            
                            <xs:element name="color" minOccurs="1" maxOccurs="1" >
                                <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="amarilla"/>
                                    <xs:enumeration value="roja"/>
                                </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="futbolista" minOccurs="1" maxOccurs="1"></xs:element>

                        </xs:sequence>    
                        </xs:complexType>
                    </xs:element>

                    <xs:element name="cambio">
                        <xs:complexType>
                        <xs:sequence>
                            <xs:element name="minuto" minOccurs="1" maxOccurs="1" type="xs:string"/>

                            <xs:element name="equipo" minOccurs="1" maxOccurs="1"></xs:element>
                            <xs:element name="lesion" minOccurs="0" maxOccurs="1">
                                <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Si"></xs:enumeration>
                                </xs:restriction>    
                                </xs:simpleType>
                            </xs:element>

                        </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    
                </xs:choice> 
                </xs:complexType>
            </xs:element>    
        </xs:sequence> 
            <xs:attribute name="id" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:ID">
                       <xs:pattern value="[p][a][r][t][i][d][o][-][0-9][0-9][0-9]"></xs:pattern>
                    </xs:restriction>
                   </xs:simpleType>   

            </xs:attribute>
        </xs:complexType>
        </xs:element>
    

        </xs:sequence>
        </xs:complexType>

    </xs:element>



</xs:schema>

=== jaimejl21/Gesti-n_Datos/Practica2_G5/XML_XSD_G5/jugadas.xml
<?xml version="1.0" encoding="UTF-8" ?>


<partidos xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="jugadas.xsd">
    <partido id='partido-001'>
        <jugadores>
            <jugador>BugFire</jugador>
            <jugador>DancingMadman</jugador>
        </jugadores>
        <equipos>
            <equipo>Boca Juniors</equipo>
            <equipo>Barcelona</equipo>
        </equipos>
        <jugadas>
            <gol>
                <minuto>2:10</minuto>
                <equipo>Barcelona</equipo>
                <futbolista>Sergi Roberto</futbolista>
            </gol>
            <cambio>
                <minuto>17:30</minuto>
                <equipo>Barcelona</equipo>
            </cambio>
        </jugadas>
    </partido>
    <partido id='partido-002'>
        <jugadores>
            <jugador>Waffle</jugador>
            <jugador>AcidGosling</jugador>
        </jugadores>
        <equipos>
            <equipo>River Plate</equipo>
            <equipo>Barcelona</equipo>
        </equipos>
        <jugadas>
            <cambio>
                <minuto>9:30</minuto>
                <equipo>Barcelona</equipo>
            </cambio>
            <cambio>
                <minuto>18:17</minuto>
                <equipo>Barcelona</equipo>
                <lesion>Si</lesion>
            </cambio>
            <tarjeta>
                <minuto>23:58</minuto>
                <color>amarilla</color>
                <futbolista>Busquets</futbolista>
            </tarjeta>
        </jugadas>
    </partido>
    <partido id='partido-003'>
        <jugadores>
            <jugador>ChocoNutsX</jugador>
            <jugador>ChipQueen</jugador>
        </jugadores>
        <equipos>
            <equipo>Manchester United</equipo>
            <equipo>PSG</equipo>
        </equipos>
        <jugadas>
            <cambio>
                <minuto>19:31</minuto>
                <equipo>Manchester United</equipo>
                <lesion>Si</lesion>
            </cambio>
            <gol>
                <minuto>27:52</minuto>
                <equipo>PSG</equipo>
                <futbolista>Marquinhos</futbolista>
            </gol>
        </jugadas>
    </partido>
    <partido id='partido-004'>
        <jugadores>
            <jugador>BabyBrown</jugador>
            <jugador>BazookaHar-de-har</jugador>
        </jugadores>
        <equipos>
            <equipo>Manchester City</equipo>
            <equipo>Real Madrid</equipo>
        </equipos>
        <jugadas>
            <gol>
                <minuto>6:33</minuto>
                <equipo>Manchester City</equipo>
                <futbolista>K.Walker</futbolista>
            </gol>
            <gol>
                <minuto>17:23</minuto>
                <equipo>Real Madrid</equipo>
                <futbolista>Asensio</futbolista>
            </gol>
            <cambio>
                <minuto>26:48</minuto>
                <equipo>Real Madrid</equipo>
            </cambio>
            <gol>
                <minuto>33:10</minuto>
                <equipo>Manchester City</equipo>
                <futbolista>Ederson Moraes</futbolista>
            </gol>
        </jugadas>
    </partido>
    <partido id='partido-005'>
        <jugadores>
            <jugador>CenturionSherman</jugador>
            <jugador>CrissCross</jugador>
        </jugadores>
        <equipos>
            <equipo>Real Madrid</equipo>
            <equipo>Juventus</equipo>
        </equipos>
        <jugadas>
            <cambio>
                <minuto>7:31</minuto>
                <equipo>Real Madrid</equipo>
            </cambio>
            <gol>
                <minuto>12:51</minuto>
                <equipo>Juventus</equipo>
                <futbolista>M.Demiral</futbolista>
            </gol>
            <cambio>
                <minuto>24:53</minuto>
                <equipo>Juventus</equipo>
            </cambio>
            <gol>
                <minuto>37:34</minuto>
                <equipo>Real Madrid</equipo>
                <futbolista>L.Modric</futbolista>
            </gol>
        </jugadas>
    </partido>
    <partido id='partido-006'>
        <jugadores>
            <jugador>AccidentalGenius</jugador>
            <jugador>BoomBlaster</jugador>
        </jugadores>
        <equipos>
            <equipo>Borussia Dortmund</equipo>
            <equipo>Juventus</equipo>
        </equipos>
        <jugadas>
            <tarjeta>
                <minuto>2:51</minuto>
                <color>amarilla</color>
                <futbolista>R.Burki</futbolista>
            </tarjeta>
            <cambio>
                <minuto>15:16</minuto>
                <equipo>Juventus</equipo>
            </cambio>
            <cambio>
                <minuto>17:41</minuto>
                <equipo>Borussia Dortmund</equipo>
            </cambio>
            <tarjeta>
                <minuto>25:54</minuto>
                <color>amarilla</color>
                <futbolista>A.Ramsey</futbolista>
            </tarjeta>
        </jugadas>
    </partido>
    <partido id='partido-007'>
        <jugadores>
            <jugador>Pixels</jugador>
            <jugador>BettyCricket</jugador>
        </jugadores>
        <equipos>
            <equipo>Juventus</equipo>
            <equipo>PSG</equipo>
        </equipos>
        <jugadas>
            <gol>
                <minuto>11:59</minuto>
                <equipo>Juventus</equipo>
                <futbolista>Morata</futbolista>
            </gol>
            <gol>
                <minuto>14:36</minuto>
                <equipo>Juventus</equipo>
                <futbolista>F.Chiesa</futbolista>
            </gol>
            <gol>
                <minuto>18:17</minuto>
                <equipo>Juventus</equipo>
                <futbolista>M.Demiral</futbolista>
            </gol>
            <cambio>
                <minuto>25:25</minuto>
                <equipo>Juventus</equipo>
            </cambio>
        </jugadas>
    </partido>
    <partido id='partido-008'>
        <jugadores>
            <jugador>AlleyFrog</jugador>
            <jugador>BeetleKing</jugador>
        </jugadores>
        <equipos>
            <equipo>Juventus</equipo>
            <equipo>Boca Juniors</equipo>
        </equipos>
        <jugadas>
            <tarjeta>
                <minuto>14:15</minuto>
                <color>amarilla</color>
                <futbolista>Cristiano Ronaldo</futbolista>
            </tarjeta>
            <tarjeta>
                <minuto>18:35</minuto>
                <color>amarilla</color>
                <futbolista>W.Szczesny</futbolista>
            </tarjeta>
            <tarjeta>
                <minuto>30:47</minuto>
                <color>roja</color>
                <futbolista>J.Campuzano</futbolista>
            </tarjeta>
        </jugadas>
    </partido>
    <partido id='partido-009'>
        <jugadores>
            <jugador>CoBolt</jugador>
            <jugador>DancingMadman</jugador>
        </jugadores>
        <equipos>
            <equipo>Boca Juniors</equipo>
            <equipo>Real Madrid</equipo>
        </equipos>
        <jugadas>
            <tarjeta>
                <minuto>9:37</minuto>
                <color>roja</color>
                <futbolista>F.Fabra</futbolista>
            </tarjeta>
            <gol>
                <minuto>23:22</minuto>
                <equipo>Boca Juniors</equipo>
                <futbolista>S.Villa</futbolista>
            </gol>
            <cambio>
                <minuto>33:53</minuto>
                <equipo>Boca Juniors</equipo>
            </cambio>
        </jugadas>
    </partido>
    <partido id='partido-010'>
        <jugadores>
            <jugador>Alpha</jugador>
            <jugador>Cujo</jugador>
        </jugadores>
        <equipos>
            <equipo>Borussia Dortmund</equipo>
            <equipo>PSG</equipo>
        </equipos>
        <jugadas>
            <cambio>
                <minuto>15:20</minuto>
                <equipo>PSG</equipo>
            </cambio>
            <cambio>
                <minuto>32:29</minuto>
                <equipo>Borussia Dortmund</equipo>
                <lesion>Si</lesion>
            </cambio>
            <cambio>
                <minuto>41:38</minuto>
                <equipo>PSG</equipo>
                <lesion>Si</lesion>
            </cambio>
        </jugadas>
    </partido>
    <partido id='partido-011'>
        <jugadores>
            <jugador>CerealKiller</jugador>
            <jugador>ChipQueen</jugador>
        </jugadores>
        <equipos>
            <equipo>Juventus</equipo>
            <equipo>Borussia Dortmund</equipo>
        </equipos>
        <jugadas>
            <tarjeta>
                <minuto>25:39</minuto>
                <color>roja</color>
                <futbolista>M.Dahoud</futbolista>
            </tarjeta>
        </jugadas>
    </partido>
    <partido id='partido-012'>
        <jugadores>
            <jugador>Dredd</jugador>
            <jugador>DriftDetector</jugador>
        </jugadores>
        <equipos>
            <equipo>Real Madrid</equipo>
            <equipo>Borussia Dortmund</equipo>
        </equipos>
        <jugadas>
            <gol>
                <minuto>13:25</minuto>
                <equipo>Borussia Dortmund</equipo>
                <futbolista>J.Sancho</futbolista>
            </gol>
            <cambio>
                <minuto>16:47</minuto>
                <equipo>Borussia Dortmund</equipo>
            </cambio>
        </jugadas>
    </partido>
    <partido id='partido-013'>
        <jugadores>
            <jugador>BeetleKing</jugador>
