=== jaimejl21/Gesti-n_Datos/Practica2_G5/XML_XSD_G5/partidos.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="partidos">
        <xs:complexType>
        <xs:sequence>
        <xs:element name="partido" maxOccurs="unbounded">
            <xs:complexType>
            <xs:sequence>

                <xs:element name="jugadores">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="jugador" type="xs:string" minOccurs="2" maxOccurs="2"/>
                    </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="equipos">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="equipo" type="xs:string" minOccurs="2" maxOccurs="2"/>
                    </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="equipoGanador" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="jugadorGanador" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="sala" type="xs:string" minOccurs="1" maxOccurs="1" />
                


            </xs:sequence>    

            <xs:attribute name="idPartido" use="required" >
                <xs:simpleType>
                 <xs:restriction base="xs:ID">
                    <xs:pattern value="[p][a][r][t][i][d][o][-][0-9][0-9][0-9]"></xs:pattern>
                 </xs:restriction>
                </xs:simpleType>   
            </xs:attribute>

            </xs:complexType>

            
        </xs:element>


        </xs:sequence>    
        </xs:complexType>
    </xs:element>




</xs:schema>

=== jaimejl21/Gesti-n_Datos/Practica2_G5/XML_XSD_G5/partidos.xml
<?xml version="1.0" encoding="UTF-8" ?>
    <partidos  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="partidos.xsd">
        <partido idPartido='partido-001'>
            <jugadores>
                <jugador>DesertHaze</jugador>
                <jugador>CerealKiller</jugador>
            </jugadores>
            <equipos>
                <equipo>Barcelona</equipo>
                <equipo>PSG</equipo>
            </equipos>
            <equipoGanador>PSG</equipoGanador>
            <jugadorGanador>CerealKiller</jugadorGanador>
            <sala>s160</sala>
        </partido>
         
        <partido idPartido='partido-002'>
            <jugadores>
                <jugador>DayHawk</jugador>
                <jugador>DonStab</jugador>
            </jugadores>
            <equipos>
                <equipo>Boca Juniors</equipo>
                <equipo>Real Madrid</equipo>
            </equipos>
            <equipoGanador>Boca Juniors</equipoGanador>
            <jugadorGanador>DayHawk</jugadorGanador>
            <sala>s119</sala>
        </partido>
         
        <partido idPartido='partido-003'>
            <jugadores>
                <jugador>Blister</jugador>
                <jugador>DarksideOrbit</jugador>
            </jugadores>
            <equipos>
                <equipo>Juventus</equipo>
                <equipo>Real Madrid</equipo>
            </equipos>
            <equipoGanador>Real Madrid</equipoGanador>
            <jugadorGanador>DarksideOrbit</jugadorGanador>
            <sala>s104</sala>
        </partido>
         
        <partido idPartido='partido-004'>
            <jugadores>
                <jugador>DonStab</jugador>
                <jugador>Digger</jugador>
            </jugadores>
            <equipos>
                <equipo>Barcelona</equipo>
                <equipo>Barcelona</equipo>
            </equipos>
            <equipoGanador>Barcelona</equipoGanador>
            <jugadorGanador>DonStab</jugadorGanador>
            <sala>s46</sala>
        </partido>
         
        <partido idPartido='partido-005'>
            <jugadores>
                <jugador>Commando</jugador>
                <jugador>DevilChick</jugador>
            </jugadores>
            <equipos>
                <equipo>River Plate</equipo>
                <equipo>Barcelona</equipo>
            </equipos>
            <equipoGanador>Barcelona</equipoGanador>
            <jugadorGanador>DevilChick</jugadorGanador>
            <sala>s109</sala>
        </partido>
         
        <partido idPartido='partido-006'>
            <jugadores>
                <jugador>ChasmFace</jugador>
                <jugador>BackBett</jugador>
            </jugadores>
            <equipos>
                <equipo>Juventus</equipo>
                <equipo>River Plate</equipo>
            </equipos>
            <equipoGanador>River Plate</equipoGanador>
            <jugadorGanador>BackBett</jugadorGanador>
            <sala>s197</sala>
        </partido>
         
        <partido idPartido='partido-007'>
            <jugadores>
                <jugador>BugBlitz</jugador>
                <jugador>DanimalDaze</jugador>
            </jugadores>
            <equipos>
                <equipo>Borussia Dortmund</equipo>
                <equipo>Barcelona</equipo>
            </equipos>
            <equipoGanador>Barcelona</equipoGanador>
            <jugadorGanador>DanimalDaze</jugadorGanador>
            <sala>s133</sala>
        </partido>
         
        <partido idPartido='partido-008'>
            <jugadores>
                <jugador>CrazyEights</jugador>
                <jugador>CandyButcher</jugador>
            </jugadores>
            <equipos>
                <equipo>Borussia Dortmund</equipo>
                <equipo>Real Madrid</equipo>
            </equipos>
            <equipoGanador>Borussia Dortmund</equipoGanador>
            <jugadorGanador>CrazyEights</jugadorGanador>
            <sala>s102</sala>
        </partido>
         
        <partido idPartido='partido-009'>
            <jugadores>
                <jugador>DozKiller</jugador>
                <jugador>AutomaticSlicer</jugador>
            </jugadores>
            <equipos>
                <equipo>PSG</equipo>
                <equipo>Borussia Dortmund</equipo>
            </equipos>
            <equipoGanador>PSG</equipoGanador>
            <jugadorGanador>DozKiller</jugadorGanador>
            <sala>s138</sala>
        </partido>
         
        <partido idPartido='partido-010'>
            <jugadores>
                <jugador>CobraBite</jugador>
                <jugador>DancingMadman</jugador>
            </jugadores>
            <equipos>
                <equipo>Juventus</equipo>
                <equipo>Juventus</equipo>
            </equipos>
            <equipoGanador>Juventus</equipoGanador>
            <jugadorGanador>DancingMadman</jugadorGanador>
            <sala>s178</sala>
        </partido>
         
        <partido idPartido='partido-011'>
            <jugadores>
                <jugador>DiscoPotato</jugador>
                <jugador>CerealKiller</jugador>
            </jugadores>
            <equipos>
                <equipo>River Plate</equipo>
                <equipo>Borussia Dortmund</equipo>
            </equipos>
            <equipoGanador>River Plate</equipoGanador>
            <jugadorGanador>DiscoPotato</jugadorGanador>
            <sala>s183</sala>
        </partido>
         
        <partido idPartido='partido-012'>
            <jugadores>
                <jugador>BadBunny</jugador>
                <jugador>CapitalF</jugador>
            </jugadores>
            <equipos>
                <equipo>Borussia Dortmund</equipo>
                <equipo>PSG</equipo>
            </equipos>
            <equipoGanador>Borussia Dortmund</equipoGanador>
            <jugadorGanador>BadBunny</jugadorGanador>
            <sala>s187</sala>
        </partido>
         
        <partido idPartido='partido-013'>
            <jugadores>
                <jugador>CelticCharger</jugador>
                <jugador>CenturionSherman</jugador>
            </jugadores>
            <equipos>
                <equipo>Boca Juniors</equipo>
                <equipo>Juventus</equipo>
            </equipos>
            <equipoGanador>Juventus</equipoGanador>
            <jugadorGanador>CenturionSherman</jugadorGanador>
            <sala>s179</sala>
        </partido>
         
        <partido idPartido='partido-014'>
            <jugadores>
                <jugador>DarkHorse</jugador>
                <jugador>CoBolt</jugador>
            </jugadores>
            <equipos>
                <equipo>Juventus</equipo>
                <equipo>Barcelona</equipo>
            </equipos>
            <equipoGanador>Barcelona</equipoGanador>
            <jugadorGanador>CoBolt</jugadorGanador>
            <sala>s15</sala>
        </partido>
         
        <partido idPartido='partido-015'>
            <jugadores>
                <jugador>DiscoMate</jugador>
                <jugador>Bowler</jugador>
            </jugadores>
            <equipos>
                <equipo>Boca Juniors</equipo>
                <equipo>Manchester United</equipo>
            </equipos>
            <equipoGanador>Boca Juniors</equipoGanador>
            <jugadorGanador>DiscoMate</jugadorGanador>
            <sala>s30</sala>
        </partido>
         
        <partido idPartido='partido-016'>
            <jugadores>
                <jugador>DiamondGamer</jugador>
                <jugador>ArsenicCoo</jugador>
            </jugadores>
            <equipos>
                <equipo>Borussia Dortmund</equipo>
                <equipo>Juventus</equipo>
            </equipos>
            <equipoGanador>Juventus</equipoGanador>
            <jugadorGanador>ArsenicCoo</jugadorGanador>
            <sala>s10</sala>
        </partido>
         
        <partido idPartido='partido-017'>
            <jugadores>
                <jugador>CerealKiller</jugador>
                <jugador>CrissCross</jugador>
            </jugadores>
            <equipos>
                <equipo>Manchester City</equipo>
                <equipo>Real Madrid</equipo>
            </equipos>
            <equipoGanador>Manchester City</equipoGanador>
            <jugadorGanador>CerealKiller</jugadorGanador>
            <sala>s117</sala>
        </partido>
         
        <partido idPartido='partido-018'>
            <jugadores>
                <jugador>Blister</jugador>
                <jugador>DevilChick</jugador>
            </jugadores>
            <equipos>
                <equipo>Real Madrid</equipo>
                <equipo>Borussia Dortmund</equipo>
            </equipos>
            <equipoGanador>Real Madrid</equipoGanador>
            <jugadorGanador>Blister</jugadorGanador>
            <sala>s143</sala>
        </partido>
         
        <partido idPartido='partido-019'>
            <jugadores>
                <jugador>Alpha</jugador>
                <jugador>Blister</jugador>
            </jugadores>
            <equipos>
                <equipo>Juventus</equipo>
                <equipo>PSG</equipo>
            </equipos>
            <equipoGanador>Juventus</equipoGanador>
            <jugadorGanador>Alpha</jugadorGanador>
            <sala>s110</sala>
        </partido>
         
        <partido idPartido='partido-020'>
            <jugadores>
                <jugador>CrossThread</jugador>
                <jugador>AirportHobo</jugador>
            </jugadores>
            <equipos>
                <equipo>River Plate</equipo>
                <equipo>Manchester United</equipo>
            </equipos>
