=== jaimejl21/Gesti-n_Datos/Practica2_G5/XML_XSD_G5/servidor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="servidores">
        <xs:complexType>
         <xs:sequence>
            <xs:element name="servidor" maxOccurs="unbounded">
                <xs:complexType>
            
                <xs:sequence>
                    <xs:element name="region" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="salas"  minOccurs="1" maxOccurs="1">
                        <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sala" type="xs:ID" minOccurs="1" maxOccurs="5"/>
                        </xs:sequence>    
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>    

                <xs:attribute name="id" use="required" >
                    <xs:simpleType>
                     <xs:restriction base="xs:ID">
                        <xs:pattern value="[s][v][-][0-9][0-9][0-9]"></xs:pattern>
                     </xs:restriction>
                    </xs:simpleType>   
                </xs:attribute>

                </xs:complexType>
 

            </xs:element>


         </xs:sequence>    
        </xs:complexType>

<!--   <xs:key name="dateAndProdNumKey">
    <xs:selector xpath="servidor"/>
    <xs:field xpath="salas/sala"/>
    <xs:field xpath="@id"/>

  </xs:key>
-->
    </xs:element>





</xs:schema>

=== jaimejl21/Gesti-n_Datos/Practica2_G5/XML_XSD_G5/servidor.xml
<?xml version="1.0" encoding="UTF-8" ?><!-- stanalone?-->

<servidores xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="servidor.xsd">
    <servidor id='sv-001'>
        <region><![CDATA[Afghanistan]]></region>
         <salas>
            <sala>s1</sala>
            <sala>s2</sala>
        </salas>
    </servidor>
    <servidor id='sv-002'>
        <region><![CDATA[Albania]]></region>
         <salas>
            <sala>s3</sala>
            <sala>s4</sala>
        </salas>
    </servidor>
    <servidor id='sv-003'>
        <region><![CDATA[Algeria]]></region>
         <salas>
            <sala>s5</sala>
            <sala>s6</sala>
        </salas>
    </servidor>
    <servidor id='sv-004'>
        <region><![CDATA[Andorra]]></region>
         <salas>
            <sala>s7</sala>
            <sala>s8</sala>
        </salas>
    </servidor>
    <servidor id='sv-005'>
        <region><![CDATA[Angola]]></region>
         <salas>
            <sala>s9</sala>
            <sala>s10</sala>
        </salas>
    </servidor>
    <servidor id='sv-006'>
        <region><![CDATA[Antigua and Barbuda]]></region>
         <salas>
            <sala>s11</sala>
            <sala>s12</sala>
        </salas>
    </servidor>
    <servidor id='sv-007'>
        <region><![CDATA[Argentina]]></region>
         <salas>
            <sala>s13</sala>
            <sala>s14</sala>
        </salas>
    </servidor>
    <servidor id='sv-008'>
        <region><![CDATA[Armenia]]></region>
         <salas>
            <sala>s15</sala>
            <sala>s16</sala>
        </salas>
    </servidor>
    <servidor id='sv-009'>
        <region><![CDATA[Australia]]></region>
         <salas>
            <sala>s17</sala>
            <sala>s18</sala>
        </salas>
    </servidor>
    <servidor id='sv-010'>
        <region><![CDATA[Austria]]></region>
         <salas>
            <sala>s19</sala>
            <sala>s20</sala>
        </salas>
    </servidor>
    <servidor id='sv-011'>
        <region><![CDATA[Austrian Empire]]></region>
         <salas>
            <sala>s21</sala>
            <sala>s22</sala>
        </salas>
    </servidor>
    <servidor id='sv-012'>
        <region><![CDATA[Azerbaijan]]></region>
         <salas>
            <sala>s23</sala>
            <sala>s24</sala>
        </salas>
    </servidor>
    <servidor id='sv-013'>
        <region><![CDATA[Bahrain]]></region>
         <salas>
            <sala>s25</sala>
            <sala>s26</sala>
        </salas>
    </servidor>
    <servidor id='sv-014'>
        <region><![CDATA[Bangladesh]]></region>
         <salas>
            <sala>s27</sala>
            <sala>s28</sala>
        </salas>
    </servidor>
    <servidor id='sv-015'>
        <region><![CDATA[Barbados]]></region>
         <salas>
            <sala>s29</sala>
            <sala>s30</sala>
        </salas>
    </servidor>
    <servidor id='sv-016'>
        <region><![CDATA[Belarus]]></region>
         <salas>
            <sala>s31</sala>
            <sala>s32</sala>
        </salas>
    </servidor>
    <servidor id='sv-017'>
        <region><![CDATA[Belgium]]></region>
         <salas>
            <sala>s33</sala>
            <sala>s34</sala>
        </salas>
    </servidor>
    <servidor id='sv-018'>
        <region><![CDATA[Belize]]></region>
         <salas>
            <sala>s35</sala>
            <sala>s36</sala>
        </salas>
    </servidor>
    <servidor id='sv-019'>
        <region><![CDATA[Benin (Dahomey)]]></region>
         <salas>
            <sala>s37</sala>
            <sala>s38</sala>
        </salas>
    </servidor>
    <servidor id='sv-020'>
        <region><![CDATA[Bolivia]]></region>
         <salas>
            <sala>s39</sala>
            <sala>s40</sala>
        </salas>
    </servidor>
    <servidor id='sv-021'>
        <region><![CDATA[Bosnia and Herzegovina]]></region>
         <salas>
            <sala>s41</sala>
            <sala>s42</sala>
        </salas>
    </servidor>
    <servidor id='sv-022'>
        <region><![CDATA[Botswana]]></region>
         <salas>
            <sala>s43</sala>
            <sala>s44</sala>
        </salas>
    </servidor>
    <servidor id='sv-023'>
        <region><![CDATA[Brazil]]></region>
         <salas>
            <sala>s45</sala>
            <sala>s46</sala>
        </salas>
    </servidor>
    <servidor id='sv-024'>
        <region><![CDATA[Brunei]]></region>
         <salas>
            <sala>s47</sala>
            <sala>s48</sala>
        </salas>
    </servidor>
    <servidor id='sv-025'>
        <region><![CDATA[Brunswick and Luneburg]]></region>
         <salas>
            <sala>s49</sala>
            <sala>s50</sala>
        </salas>
    </servidor>
    <servidor id='sv-026'>
        <region><![CDATA[Bulgaria]]></region>
         <salas>
            <sala>s51</sala>
            <sala>s52</sala>
        </salas>
    </servidor>
    <servidor id='sv-027'>
        <region><![CDATA[Burkina Faso (Upper Volta)]]></region>
         <salas>
            <sala>s53</sala>
            <sala>s54</sala>
        </salas>
    </servidor>
    <servidor id='sv-028'>
        <region><![CDATA[Burma]]></region>
         <salas>
            <sala>s55</sala>
            <sala>s56</sala>
        </salas>
    </servidor>
    <servidor id='sv-029'>
        <region><![CDATA[Burundi]]></region>
         <salas>
            <sala>s57</sala>
            <sala>s58</sala>
        </salas>
    </servidor>
    <servidor id='sv-030'>
        <region><![CDATA[Cabo Verde]]></region>
         <salas>
            <sala>s59</sala>
            <sala>s60</sala>
        </salas>
    </servidor>
    <servidor id='sv-031'>
        <region><![CDATA[Cambodia]]></region>
         <salas>
            <sala>s61</sala>
            <sala>s62</sala>
        </salas>
    </servidor>
    <servidor id='sv-032'>
        <region><![CDATA[Cameroon]]></region>
         <salas>
            <sala>s63</sala>
            <sala>s64</sala>
        </salas>
    </servidor>
    <servidor id='sv-033'>
        <region><![CDATA[Canada]]></region>
         <salas>
            <sala>s65</sala>
            <sala>s66</sala>
        </salas>
    </servidor>
    <servidor id='sv-034'>
        <region><![CDATA[Chad]]></region>
         <salas>
            <sala>s67</sala>
            <sala>s68</sala>
        </salas>
    </servidor>
    <servidor id='sv-035'>
        <region><![CDATA[Chile]]></region>
         <salas>
            <sala>s69</sala>
            <sala>s70</sala>
        </salas>
    </servidor>
    <servidor id='sv-036'>
        <region><![CDATA[China]]></region>
         <salas>
            <sala>s71</sala>
            <sala>s72</sala>
        </salas>
    </servidor>
    <servidor id='sv-037'>
        <region><![CDATA[Colombia]]></region>
         <salas>
            <sala>s73</sala>
            <sala>s74</sala>
        </salas>
    </servidor>
    <servidor id='sv-038'>
        <region><![CDATA[Comoros]]></region>
         <salas>
            <sala>s75</sala>
            <sala>s76</sala>
        </salas>
    </servidor>
    <servidor id='sv-039'>
        <region><![CDATA[Costa Rica]]></region>
         <salas>
            <sala>s77</sala>
            <sala>s78</sala>
        </salas>
    </servidor>
    <servidor id='sv-040'>
        <region><![CDATA[Croatia]]></region>
         <salas>
            <sala>s79</sala>
            <sala>s80</sala>
        </salas>
    </servidor>
    <servidor id='sv-041'>
        <region><![CDATA[Cuba]]></region>
         <salas>
            <sala>s81</sala>
            <sala>s82</sala>
        </salas>
    </servidor>
    <servidor id='sv-042'>
        <region><![CDATA[Cyprus]]></region>
         <salas>
            <sala>s83</sala>
            <sala>s84</sala>
        </salas>
    </servidor>
    <servidor id='sv-043'>
        <region><![CDATA[Czechia]]></region>
         <salas>
            <sala>s85</sala>
            <sala>s86</sala>
        </salas>
    </servidor>
    <servidor id='sv-044'>
        <region><![CDATA[Czechoslovakia]]></region>
         <salas>
            <sala>s87</sala>
            <sala>s88</sala>
        </salas>
    </servidor>
    <servidor id='sv-045'>
        <region><![CDATA[Democratic Republic of the Congo]]></region>
         <salas>
            <sala>s89</sala>
            <sala>s90</sala>
        </salas>
    </servidor>
    <servidor id='sv-046'>
        <region><![CDATA[Denmark]]></region>
         <salas>
            <sala>s91</sala>
            <sala>s92</sala>
        </salas>
    </servidor>
    <servidor id='sv-047'>
        <region><![CDATA[Djibouti]]></region>
         <salas>
            <sala>s93</sala>
            <sala>s94</sala>
        </salas>
    </servidor>
    <servidor id='sv-048'>
        <region><![CDATA[Dominica]]></region>
         <salas>
            <sala>s95</sala>
            <sala>s96</sala>
        </salas>
    </servidor>
    <servidor id='sv-049'>
        <region><![CDATA[Dominican Republic]]></region>
         <salas>
            <sala>s97</sala>
            <sala>s98</sala>
        </salas>
    </servidor>
    <servidor id='sv-050'>
        <region><![CDATA[Ecuador]]></region>
         <salas>
            <sala>s99</sala>
            <sala>s100</sala>
        </salas>
    </servidor>
    <servidor id='sv-051'>
        <region><![CDATA[Egypt]]></region>
         <salas>
            <sala>s101</sala>
            <sala>s102</sala>
        </salas>
    </servidor>
    <servidor id='sv-052'>
        <region><![CDATA[El Salvador]]></region>
         <salas>
            <sala>s103</sala>
            <sala>s104</sala>
